kind: Deployment
apiVersion: apps/v1
metadata:
   name: nikita
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: nikita
   template:
      metadata:
        labels:
          app: nikita
      spec:
       containers:
        - name: nikita
          image: nikitafordocker/webapp-k8s
          imagePullPolicy: Always
          ports:
          - containerPort: 80