kind: Service                             
apiVersion: v1
metadata:
  name: nikita
  labels:
    app: nikita
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: nikita                    
  type: LoadBalancer    